package mibprojekt;

import javax.swing.JOptionPane;
import oru.inf.InfException;
import oru.inf.InfDB;
import oru.inf.InfException;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author trnfa
 */
public class Inlogg extends javax.swing.JFrame {

    private InfDB idb;
       
    public Inlogg(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonLogOn = new javax.swing.JToggleButton();
        fieldName = new javax.swing.JTextField();
        labelName = new javax.swing.JLabel();
        labelPW = new javax.swing.JLabel();
        fieldPW = new javax.swing.JPasswordField();
        cbAgent = new javax.swing.JCheckBox();
        cbAlien = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonLogOn.setText("Log in");
        buttonLogOn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogOnActionPerformed(evt);
            }
        });
        getContentPane().add(buttonLogOn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 270, 105, 30));
        getContentPane().add(fieldName, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 112, -1));

        labelName.setText("Name:");
        getContentPane().add(labelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 170, -1, -1));

        labelPW.setText("Password:");
        getContentPane().add(labelPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, -1, 20));
        getContentPane().add(fieldPW, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 112, -1));

        cbAgent.setBackground(new java.awt.Color(71, 108, 111));
        buttonGroup1.add(cbAgent);
        cbAgent.setText("Agent");
        getContentPane().add(cbAgent, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 120, 81, 30));

        cbAlien.setBackground(new java.awt.Color(71, 108, 111));
        buttonGroup1.add(cbAlien);
        cbAlien.setText("Alien");
        getContentPane().add(cbAlien, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 81, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\trnfa\\Desktop\\MIBPROJECT\\MIBAPPLICATION\\Inloggningsruta.png")); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-6, -6, 680, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//HEJHEJ TEST SER NI?
    private void buttonLogOnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogOnActionPerformed
    
        boolean categoryPicked = true;
        String tabell = null;
        String id = null;
        String isAdminCheck = null;
        boolean inloggChoice = false;
        LoggedUser user;
        
        if (Validering.textFaltHarVarde(fieldName) && Validering.textFaltHarVarde(fieldPW)){
            try{
                String namnAnvandare = fieldName.getText();
                String losenord = fieldPW.getText();
                               
                if(cbAgent.isSelected()){
                     inloggChoice = true;
                     tabell = "agent";
                     id = "agent_ID";
                }
                else if (cbAlien.isSelected()){
                     tabell = "alien";
                     id = "alien_ID";
                }
                else {
                    categoryPicked = false;
                    JOptionPane.showMessageDialog(null, "Pick a category");
                }
                
                String svarID = idb.fetchSingle("SELECT "+ id + " FROM " + tabell +" WHERE Namn= '" + namnAnvandare + "'");
                String losenordTva = idb.fetchSingle("SELECT Losenord FROM " + tabell + " WHERE " + id + " = " + svarID); 
                isAdminCheck = idb.fetchSingle("Select Administrator FROM agent WHERE Agent_ID =" + svarID);
                     
                if (losenordTva.equals(losenord)){
                    if(!inloggChoice){
                        user =  new LoggedUser(idb, svarID, losenordTva, true, false);
                        new Startsida_Alien(idb).setVisible(true);                        
                    }
                    
                    else if(inloggChoice&& isAdminCheck.equals("J")){
                        user =  new LoggedUser(idb, svarID, losenordTva, false, true);
                        new Startsida_Admin(idb).setVisible(true);                        
                    }
           
                    else if(inloggChoice && isAdminCheck.equals("N")){   
                        user =  new LoggedUser(idb, svarID, losenordTva, false, false);
                        new Startsida_Agent(idb).setVisible(true); 
                    }
                    dispose();
                }
                else
                    JOptionPane.showMessageDialog(null, "You have entered wrong password.");  
            }
            catch(NullPointerException ettUndantag){
                JOptionPane.showMessageDialog(null, "You have entered wrong username or category.");            
            }
            
            catch (Exception annatUndantag){
                if(categoryPicked){
                JOptionPane.showMessageDialog(null, "Something went wrong. Please contact your IT-Administrator.");
                System.out.println("InternFelmeddelande:" + annatUndantag.getMessage());
                }
            }
        }
    }//GEN-LAST:event_buttonLogOnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inlogg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
             //   new Inlogg(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JToggleButton buttonLogOn;
    private javax.swing.JCheckBox cbAgent;
    private javax.swing.JCheckBox cbAlien;
    private javax.swing.JTextField fieldName;
    private javax.swing.JPasswordField fieldPW;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelPW;
    // End of variables declaration//GEN-END:variables
}
