/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mibprojekt;

import javax.swing.JOptionPane;
import oru.inf.InfDB;

/**
 *
 * @author trnfa
 */
public class RegUtrustning extends javax.swing.JFrame {

    private static InfDB idb;
    private static int utrustningID;
    private static String benamning;
    /**
     * Creates new form RegUtrustning
     */
    public RegUtrustning(InfDB idb) {
        this.idb = idb;
        initComponents();
        setUtrustningsID();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUtrustingID = new javax.swing.JLabel();
        lblBenamning = new javax.swing.JLabel();
        btnOK = new javax.swing.JButton();
        lblVisaID = new javax.swing.JLabel();
        txtBenamning = new javax.swing.JTextField();
        cbKategori = new javax.swing.JComboBox<>();
        lblKategori = new javax.swing.JLabel();
        lblEgenskap = new javax.swing.JLabel();
        txtEgenskap = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUtrustingID.setText("Utrustnings ID:");

        lblBenamning.setText("Benämning:");

        btnOK.setText("OK");
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });

        cbKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Vapen", "Teknik", "Kommunikation" }));
        cbKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbKategoriActionPerformed(evt);
            }
        });

        lblKategori.setText("Kategori:");

        lblEgenskap.setText("Kaliber:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblUtrustingID)
                                .addGap(43, 43, 43)
                                .addComponent(lblVisaID, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblKategori)
                                .addComponent(lblBenamning))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(lblEgenskap, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtBenamning, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                            .addComponent(cbKategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtEgenskap))))
                .addContainerGap(114, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblVisaID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblUtrustingID))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBenamning)
                    .addComponent(txtBenamning, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKategori))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEgenskap)
                    .addComponent(txtEgenskap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(btnOK)
                .addGap(66, 66, 66))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        if (setBenamning() && setKategori(String.valueOf(cbKategori.getSelectedItem()))){
                try{
                idb.fetchSingle("INSERT INTO utrustning (Utrustnings_ID, Benamning)"
                    + "Values (" + utrustningID + ", ' " + benamning + "' )");
                    System.out.println("OK");
                    dispose();
                }
                
                catch (Exception ettUndantag){
                    System.out.println("InternFelmeddelande:" + ettUndantag.getMessage());  
                }
            }
    }//GEN-LAST:event_btnOKActionPerformed
    private boolean setKategori(String kategori){
        boolean ok = false;
        try{
            switch(kategori){
                case"Vapen":
                    if(Validering.isHeltal(txtEgenskap)){
                    idb.fetchSingle("INSERT INTO vapen (Utrustnings_ID, Kaliber) VALUES(" + utrustningID + ", " + txtEgenskap.getText() + ");");
                    }
                    break;
                case"Teknik":
                    if(Validering.textFaltHarVarde(txtEgenskap) && Validering.txtHarInteBaraSpace(txtEgenskap)){
                        idb.fetchSingle("INSERT INTO Teknik(Utrustnings_ID, Kraftkalla) VALUES (" + utrustningID + ", '" + txtEgenskap.getText() + "');");
                    }
                    break;
                case"Kommunikation":
                    if (Validering.textFaltHarVarde(txtEgenskap) && Validering.txtHarInteBaraSpace(txtEgenskap)){
                        idb.fetchSingle("INSERT INTO Kommunikation (Utrustnings_ID, Overforingsteknik) VALUES (" + utrustningID + ", '"+ txtEgenskap.getText() + "');");
                    }
                    break;  
            }
            ok = true;
        }
        catch(Exception e){
            
        }
        return ok;
    }
    private void cbKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbKategoriActionPerformed
        String selectedItem = String.valueOf(cbKategori.getSelectedItem());    
        switch(selectedItem){
            case"Vapen":
                lblEgenskap.setText("Kaliber: ");
                break;
            case"Teknik":
                lblEgenskap.setText("Kraftkalla: ");
                break;
            case"Kommunikation":
                lblEgenskap.setText("Överföringsteknik: ");
                break;
        }
    }//GEN-LAST:event_cbKategoriActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegUtrustning.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegUtrustning(idb).setVisible(true);
            }
        });
    }

    public boolean setUtrustningsID(){
        boolean ok = true;
        try{
            int nyttID = Integer.parseInt(idb.fetchSingle("Select MAX(Utrustnings_ID) from utrustning"));
            nyttID++;
            utrustningID = nyttID;
            lblVisaID.setText(String.valueOf(utrustningID));
        }
        catch(Exception ettUndantag){
            JOptionPane.showMessageDialog(null, "Something went wrong. Please contact your IT-Administrator. is not Alien");
            System.out.println("InternFelmeddelande:" + ettUndantag.getMessage());         
            ok = false;
        }
        return ok;
    }
    
    public boolean setBenamning(){
        if(Validering.textFaltHarVarde(txtBenamning) && Validering.txtHarInteBaraSpace(txtBenamning)&& Validering.okTxtLang(txtBenamning)){
            benamning = txtBenamning.getText();
            return true;
        }  
        return false;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JComboBox<String> cbKategori;
    private javax.swing.JLabel lblBenamning;
    private javax.swing.JLabel lblEgenskap;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblUtrustingID;
    private javax.swing.JLabel lblVisaID;
    private javax.swing.JTextField txtBenamning;
    private javax.swing.JTextField txtEgenskap;
    // End of variables declaration//GEN-END:variables
}
