/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mibprojekt;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author trnfa
 */
public class RegAlien extends javax.swing.JFrame {

    /**
     * Creates new form RegAlien
     */
    private static InfDB idb;
    
    private static int alienID;
    private static String regDate;
    private static String losen;
    private static String namn;
    private static String telefon;
    private static int omrade;
    private static String ansvarigAgent;
    
    public RegAlien(InfDB idb) {
        initComponents();
        this.idb = idb;
        setAlienID();
        setAnsvarigAgent();
        setDate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAlienNamn = new javax.swing.JLabel();
        comboOmrade = new javax.swing.JComboBox<>();
        lblAlienID = new javax.swing.JLabel();
        lblTelnummer = new javax.swing.JLabel();
        lbllRegDatum = new javax.swing.JLabel();
        lblPlaceras = new javax.swing.JLabel();
        lblLosen = new javax.swing.JLabel();
        lblAnsvarigAgent = new javax.swing.JLabel();
        btnReg = new javax.swing.JButton();
        txtTelefon = new javax.swing.JTextField();
        txtNamn = new javax.swing.JTextField();
        txtLosen = new javax.swing.JPasswordField();
        txtLosenUpp = new javax.swing.JPasswordField();
        lblLosenUpp = new javax.swing.JLabel();
        lblVisaAnsvarigAgent = new javax.swing.JLabel();
        lblVisaDatum = new javax.swing.JLabel();
        lblVisaID = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblAlienNamn.setText("Alien Namn:");

        comboOmrade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Örebro", "Västerås", "Vilhelmina", "Borås" }));
        comboOmrade.setDoubleBuffered(true);

        lblAlienID.setText("Alien, ID");

        lblTelnummer.setText("Telefonnummer");

        lbllRegDatum.setText("regdatum");

        lblPlaceras.setText("Placeras i");

        lblLosen.setText("Lösenord:");

        lblAnsvarigAgent.setText("ansvarig agent");

        btnReg.setText("OK");
        btnReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegActionPerformed(evt);
            }
        });

        lblLosenUpp.setText("upprepa");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(lblLosen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtLosen, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblTelnummer)
                                    .addComponent(lblAlienNamn)
                                    .addComponent(lblPlaceras)
                                    .addComponent(lblAlienID))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(comboOmrade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtTelefon)
                                            .addComponent(txtNamn)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(61, 61, 61)
                                        .addComponent(lblVisaID)))
                                .addGap(19, 19, 19))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblAnsvarigAgent)
                                .addComponent(lblVisaAnsvarigAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblLosenUpp)
                        .addGap(18, 18, 18)
                        .addComponent(txtLosenUpp, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(91, 91, 91))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblVisaDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(205, 205, 205))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lbllRegDatum)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(223, 223, 223)
                .addComponent(btnReg, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlienID)
                    .addComponent(lblVisaID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAlienNamn)
                    .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelnummer)
                    .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlaceras)
                    .addComponent(comboOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLosen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLosen)
                    .addComponent(txtLosenUpp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblLosenUpp))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblVisaAnsvarigAgent)
                    .addComponent(lblVisaDatum))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbllRegDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnsvarigAgent))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(btnReg)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegActionPerformed
        if (setPW() && setNamn() && setTelefon()){
            setOmrade();
                try{
                idb.fetchSingle("INSERT INTO alien (Alien_ID, Registreringsdatum, Losenord, Namn, Telefon, Plats, Ansvarig_agent)"
                    + "Values (" + alienID + ", ' " + regDate + "' , '" + losen + "' , '" + namn + "' , " + telefon + ", " + omrade + ", " + ansvarigAgent + ")");
                    System.out.println("OK");
                    dispose();
                }
                
                catch (Exception ettUndantag){
                    System.out.println("InternFelmeddelande:" + ettUndantag.getMessage());  
                }
            }
    }//GEN-LAST:event_btnRegActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegAlien(idb).setVisible(true);
            }
        });
    }
    public void setDate(){
        regDate = "2022-05-19";
        lblVisaDatum.setText(regDate);
    }
    
    public boolean setAlienID(){
        boolean ok = true;
        try{
            int nyttID = Integer.parseInt(idb.fetchSingle("Select MAX(Alien_ID) from Alien"));
            nyttID++;
            alienID = nyttID;
            lblVisaID.setText(String.valueOf(alienID));
        }
        catch(Exception ettUndantag){
            JOptionPane.showMessageDialog(null, "Something went wrong. Please contact your IT-Administrator. is not Alien");
            System.out.println("InternFelmeddelande:" + ettUndantag.getMessage());         
            ok = false;
        }
        return ok;
    }
    
    public boolean setAnsvarigAgent(){
        boolean ok = true;
        try{
           lblVisaAnsvarigAgent.setText(idb.fetchSingle("SELECT Namn FROM Agent WHERE Agent_ID = '" + LoggedUser.getUserID() + "'"));
           ansvarigAgent = LoggedUser.getUserID();
        }
        catch(Exception ettUndantag){
            JOptionPane.showMessageDialog(null, "Something went wrong. Please contact your IT-Administrator. is not Alien");
            System.out.println("InternFelmeddelande:" + ettUndantag.getMessage());       
            ok = false;
        }
        return ok;
    }
    
    public boolean setPW(){
        boolean ok = true;
        String newPW = txtLosen.getText();
        String newPWUpp = txtLosenUpp.getText();
        
        if(Validering.losenOK(txtLosen)){
            if(newPW.equals(newPWUpp)){
                losen = newPW;
            }
            else{
                JOptionPane.showMessageDialog(null, "The two passwords does not match");
                ok = false;
            }
        } 
        else{
            ok = false;
        }
        return ok;
    }
    
    public boolean setNamn(){
        boolean ok = false;
        String forslagNamn = txtNamn.getText();
        if (Validering.textFaltHarVarde(txtNamn) && Validering.txtHarInteBaraSpace(txtNamn)){
           try {
                String nr = idb.fetchSingle("SELECT count(*) from alien where namn = '"+ forslagNamn + "'");
                int antal = Integer.valueOf(nr);
                if (antal == 0){
                    namn = forslagNamn;
                    ok = true;
                }
                else{
                    JOptionPane.showMessageDialog(null, "Please chose an unique name for the Alien.");
                }     
            }
            catch(Exception ettUndantag){
            JOptionPane.showMessageDialog(null, "Something went wrong");         
            }
        }
        return ok;
    }  
    public void setOmrade(){
        String plats = comboOmrade.getSelectedItem().toString();
        switch(plats){
            case "Örebro":
                omrade = 1;
                break;
            case "Västerås":
                omrade = 2;
                break;
            case "Vilhelmina":
                omrade = 3;
                break;
            case "Borås":
                omrade = 4;
                break;
        }              
    }
    public boolean setTelefon(){    
        boolean resultat = false;
        if (txtTelefon.getText().equals("")){
            telefon = null;
            resultat = true;
        }
        else if(Validering.okPhoneNumber(txtTelefon)){
            telefon = txtTelefon.getText();
            resultat = true;
        }
        return resultat;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReg;
    private javax.swing.JComboBox<String> comboOmrade;
    private javax.swing.JLabel lblAlienID;
    private javax.swing.JLabel lblAlienNamn;
    private javax.swing.JLabel lblAnsvarigAgent;
    private javax.swing.JLabel lblLosen;
    private javax.swing.JLabel lblLosenUpp;
    private javax.swing.JLabel lblPlaceras;
    private javax.swing.JLabel lblTelnummer;
    private javax.swing.JLabel lblVisaAnsvarigAgent;
    private javax.swing.JLabel lblVisaDatum;
    private javax.swing.JLabel lblVisaID;
    private javax.swing.JLabel lbllRegDatum;
    private javax.swing.JPasswordField txtLosen;
    private javax.swing.JPasswordField txtLosenUpp;
    private javax.swing.JTextField txtNamn;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
