/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mibprojekt;

import javax.swing.JCheckBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import oru.inf.InfDB;

/**
 *
 * @author trnfa
 */
public class SokAgentAlien extends javax.swing.JFrame {

    /**
     * Creates new form sokAgent
     */
    private JCheckBox cbChoice;

    private InfDB idb;
  
    private String category;
    private String id;
    private String ras = null;
    
    public SokAgentAlien(InfDB idb, String id, String category) {
        this.idb = idb;
        this.id = id;
        this.category = category;
      //  fillRuta();
        initComponents();
        fyllRutor();
    }
    private String getRas(){
        try {
            String isWorm = idb.fetchSingle("SELECT * from worm where alien_ID = " + id);
            String isSquid = idb.fetchSingle("Select * from squid where alien_ID = " + id);
            String isBoglodite = idb.fetchSingle("Select * from boglodite where alien_Id = " + id);
            System.out.println(isWorm + isSquid + isBoglodite);
            
            if(isWorm != null)
                ras = "worm";
            else if (isSquid != null)
                ras = "squid";
            else if (isBoglodite != null)
                ras = "boglodite";
            else    
                System.out.println("error");
        }
        catch (Exception e){
            System.out.println("InternFelmeddelande:" + e.getMessage());
        }    
        return ras;
    }
    //boglodite
    //Antal_boogies
    private String getRasBenamning(){
        String ben = " ";
        try{
            switch(ras){
                case"squid":
                    ben = "Antal Armanr: " + idb.fetchSingle("Select antal_armar from squid where alien_id = " + id);
                    break;
                case"boglodite":
                    ben = "Antal Boogies: " + idb.fetchSingle("Select antal_boogies from boglodite where alien_id = " + id);
                    break;
            }
        }
        catch(Exception e){
            System.out.println("error");
        }
        return ben;
    }
    
    private void fyllRutor(){
        lblID.setText("ID: " + id);
        lblNamn.setText("Namn: " + getInfo("namn"));
        lblTele.setText("Telefon: " + getInfo("telefon"));
        
        switch(category){
            case "alien":
                lblDatum.setText("Registreringsdatum: " + getInfo("registreringsdatum"));
                lblOmrade.setText("Plats: " + getInfo("plats"));
                lblRas.setText("Ras: " + getRas());
                lblRasBenamning.setText(getRasBenamning());
                lblAnsvarig.setText("Ansvarig Agent: " + getInfo("ansvarig_agent"));
                lblIsAdmin.setText(" ");
                break;
            case "agent":
                lblDatum.setText("Anställningsdatum: " + getInfo("anstallningsdatum"));
                lblOmrade.setText("Område: " + getInfo("omrade"));
                lblIsAdmin.setText("Är Admin: " + getInfo("administrator"));
                lblRas.setText(" ");
                lblAnsvarig.setText(" ");
                lblRasBenamning.setText(" ");
        }
    }

    private String getInfo(String get){
        String svar = null;
        try{
            switch(category){
                case "agent":
                    svar = idb.fetchSingle("SELECT "+ get + " from agent where agent_id = "+ id); 
                    break;
                case "alien":
                    svar = idb.fetchSingle("SELECT " + get + " from alien where alien_id = " + id);
                    break;
            }
        }
        catch(Exception ettUndantag){
            System.out.println("OJ");
        }
        return svar;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnEdit = new javax.swing.JButton();
        lblNamn = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        lblTele = new javax.swing.JLabel();
        lblOmrade = new javax.swing.JLabel();
        lblAnsvarig = new javax.swing.JLabel();
        lblRas = new javax.swing.JLabel();
        lblDatum = new javax.swing.JLabel();
        lblIsAdmin = new javax.swing.JLabel();
        lblRasBenamning = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 210, 73, -1));

        lblNamn.setText("Namn:");
        getContentPane().add(lblNamn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, 20));

        lblID.setText("ID:");
        getContentPane().add(lblID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 10, -1, -1));

        lblTele.setText("Telefon:");
        getContentPane().add(lblTele, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        lblOmrade.setText("Område:");
        getContentPane().add(lblOmrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        lblAnsvarig.setText("Ansvarig agent:");
        getContentPane().add(lblAnsvarig, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, -1, -1));

        lblRas.setText("Ras:");
        getContentPane().add(lblRas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        lblDatum.setText("RegDatum:");
        getContentPane().add(lblDatum, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        lblIsAdmin.setText("Är Admin:");
        getContentPane().add(lblIsAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));

        lblRasBenamning.setText("benamning");
        getContentPane().add(lblRasBenamning, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 70, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        //switch(category){
         //   case"agent":
                new EditAgent(idb, getInfo("namn"),id,getInfo("anstallningsdatum"),getInfo("telefon"), getInfo("omrade"), getInfo("administrator")).setVisible(true);
       // }
    }//GEN-LAST:event_btnEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SokAgentAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SokAgentAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SokAgentAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SokAgentAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new SokAgentAlien(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEdit;
    private javax.swing.JLabel lblAnsvarig;
    private javax.swing.JLabel lblDatum;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIsAdmin;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblOmrade;
    private javax.swing.JLabel lblRas;
    private javax.swing.JLabel lblRasBenamning;
    private javax.swing.JLabel lblTele;
    // End of variables declaration//GEN-END:variables
}
